services:
  - type: worker
    name: numpybot-mcq
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -u bot.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
